name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt BigQuery
        run: |
          pip install dbt-bigquery

      - name: Install dependencies
        run: |
          dbt deps --project-dir recipes_dbt

      - name: Create service account file
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          recipes_dbt:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: crested-guru-480812-h2
                dataset: recipe_dw
                threads: 1
                keyfile: $(pwd)/gcp-key.json
                timeout_seconds: 300
                location: US
          EOF


      - name: Run dbt build
        run: |
          dbt build --project-dir recipes_dbt

